### ISSUE TITLE
how about the detection rate on tx2 using this way

### ISSUE THREAD

**Issue by yilawu** [gaodechen/webcam_yolov3_jetson_tx_hikvision#3]

**Comment by gaodechen** [comment]
Code has been updated, and here is my way:

```python
def predict(raw_q, pred_q):
    model = Model()
    while True:
        tic = time.time()
        raw_img = raw_q.get()
        pred_img = model.predict(raw_img)
        pred_q.put(pred_img)
        toc = time.time()
        time_cost = toc - tic
        print('Processed in %.3fs FPS = %.3f' % (time_cost, 1 / time_cost))
```

As raw_q can be blocked by get() method, wrapping get() and model.predict() with timing would make both blocking and inference counted in total time.

Or you can just count with time of predict().

I can't see the difference because time costs mainly on making predictions, which means computation on it can be accurate enough.

Hope it works for you!
